### ISSUE TITLE
dubbo-admin中不能发现服务列表？

### ISSUE THREAD

**Issue by 276234199** [apache/dubbo-spring-boot-project#212]
consumer已经可以成功调用服务。

对dubbo-admin是否有版本要求？

**Comment by 276234199** [comment]
我发现。。似乎不用zookeeper也能注册消费服务 有网址介绍下这个项目吗  我已经蒙蔽

**Comment by cwdtom** [comment]
确定下你的admin观察的group和你注册的是否一致，我之前也碰到过

**Comment by ettingshausen** [comment]
需要在provider的配置文件中配置 `dubbo.metadata-report.address`

**Comment by skycyang** [comment]
我之前遇到过，去除registry的group配置就好了
