### ISSUE TITLE
dubbo filter 配置不生效，最好整合日志slf4j，能有个像springcloud一样的traceId 日志追踪链

### ISSUE THREAD

**Issue by houhuacheng** [apache/dubbo-spring-boot-project#355]

**Comment by mercyblitz** [comment]
How to configure it?

**Comment by houhuacheng** [comment]
springboot：2.0.5.RELEASE
 <dependency>
     <groupId>com.alibaba.boot</groupId>
     <artifactId>dubbo-spring-boot-starter</artifactId>
     <version>0.2.0</version>
 </dependency>
 
 
1.继承接口com.alibaba.dubbo.rpc.Filter实现public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException 方法
加上@Activate注解

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {

        logger.info("111111111111111111111111");
        String tarceId = MDC.get(TraceConstant.TraceId);
        Map<String, String> attachments = invocation.getAttachments();
        attachments.put(TraceConstant.TraceId, tarceId);
        Result result=invoker.invoke(invocation);
        logger.info("222222222222222222222222");
        return result;

    }
2.配置文件修改
在resources目录下添加纯文本文件META-INF/dubbo/com.alibaba.dubbo.rpc.Filter
例如：traceIdFilter=com.xxx.TraceIdFilter
3.使用：
application.properties 配置 添加
dubbo.provider.filter =traceIdFilter   无效 不能注入filter  不能打印数字


@Reference(check = false,filter = traceIdFilter)依然无效

**Comment by kexianjun** [comment]
It seems your custom Filter does not work, pls refer to http://dubbo.incubator.apache.org/zh-cn/docs/dev/impls/filter.html. If you still have problems, please upload a demo for us.

**Comment by kele6413430** [comment]
It seems that you using logback  and what  you need is zipkin.
Recently,I have update the brave instrument zipkin for dubbo rpc working with dubbo 2.7.
Please send an email to me,I would like to share the new  version with you
my email is kele6431430@163.com

**Comment by ShenFeng312** [comment]
相同问题 filter 无效

**Comment by 294033186** [comment]
2.7.8 dubbo springboot配置 dubbo.provider.filter无效，使用@dubboservice（filter=xxx）可以生效

**Comment by 294033186** [comment]
https://github.com/apache/dubbo-spring-boot-project/issues/355#issuecomment-792568671 @mercyblitz 大佬目前发现服务注册和消费暴漏之后 才会去setfilter

**Comment by 294033186** [comment]
@mercyblitz 
您好，经过调试发现由于org.apache.dubbo.config.AbstractServiceConfig.getFilter上增加了@Parameter(key = SERVICE_FILTER_KEY, append = true)导致dubbo.provider.filter配置无效，去掉之后就可以了，请问这个注解有什么特殊作用吗

**Comment by 294033186** [comment]
同理去掉org.apache.dubbo.config.AbstractReferenceConfig. getFilter上的@Parameter(key = REFERENCE_FILTER_KEY, append = true)注解，dubbo.consumer.filter也可以生效了

**Comment by Notelzg** [comment]
> 同理去掉org.apache.dubbo.config.AbstractReferenceConfig. getFilter上的@parameter(key = REFERENCE_FILTER_KEY, append = true)注解，dubbo.consumer.filter也可以生效了

请问是如何去掉这个注解？
