### ISSUE TITLE
spring-boot 2.0.0 可以支持？

### ISSUE THREAD

**Issue by dazi005** [apache/dubbo-spring-boot-project#37]

**Comment by mercyblitz** [comment]
WILL DO

**Comment by BeeKun** [comment]
小马哥准备什么时候支持Spring-boot 2.0版本,以及dubbo的最新2.6.0?我自己在本地尝试之后发现之前org.springframework.boot.bind这个package已经不可用了,所以配置方法RelaxedPropertyResolver也报错,还是抓紧支持吧!
