### ISSUE TITLE
注解配置无效且无法启动

### ISSUE THREAD

**Issue by yexueyouling** [apache/dubbo-spring-boot-project#381]
按照注解配置，使用Springboot，搭建了两个工程，一个消费者，一个服务者，并且创建了一个zookeeper容器。结构如下：

![image](https://user-images.githubusercontent.com/26735625/51016895-f7f38280-15ac-11e9-9367-1cceca276c05.png)

服务者可以正常启动。
消费者启动失败，有两个错误问题
1、@reference无法注入服务者的服务。
2、启动报错：Duplicate application configs: <dubbo:application name="service-dUbbo-custom" id="service-dUbbo-custom" /> and <dubbo:application qosEnable="false" />

完全不知道是什么原因。

源码：
消费者：https://github.com/yexueyouling/service-dobbo-custom.git
服务者：https://github.com/yexueyouling/service-dobbo-server.git

**Comment by cwdtom** [comment]
<dubbo:application name="service-dUbbo-custom" id="service-dUbbo-custom" qosEnable="false"/>
