### ISSUE TITLE
注解和xml配置方式无法混合使用, 启动提示配置重复

### ISSUE THREAD

**Issue by lkqm** [apache/dubbo-spring-boot-project#382]
在一个dubbo项目中, 我通过dubbo-spring-boot-starter进行配置后使用@Service来暴露一个服务, 同时又希望通过配置的方式来定义<dubbo:reference>, 当这样做的时候, 出现了2种错误, 大致就是配置重复, 如果不在xml配置<dubbo:application>就提示配置为null, 有什么好的建议吗？

dubbo-spring-boot-starter版本: 0.1.1

配置dubbo-consumer.xml:

![image](https://user-images.githubusercontent.com/20638840/51093942-6d489880-17e3-11e9-9c6b-857c9c74ee87.png)

错误提示:
![image](https://user-images.githubusercontent.com/20638840/51093970-9ff29100-17e3-11e9-813e-33de8c75619d.png)

**Comment by mercyblitz** [comment]
You can remove the XML element `<dubbo:application>` or `spring.application.name` for resolving this issue.
