### ISSUE TITLE
Dubbo Spring Boot中@Reference和@Service命名问题

### ISSUE THREAD

**Issue by linux-china** [apache/dubbo-spring-boot-project#447]
看readme中的demo
```
@Service(version = "1.0.0")
public class DefaultDemoService implements DemoService {

```
这个@Service 和Spring中的@Repository和@Service太容易混淆啦。 个人是建议调整为 @DubboService 和 @DubboReference 
```
org.apache.dubbo.config.annotation.Service
org.apache.dubbo.config.annotation.Reference
```
Spring Boot和其他的RPC框架整合的Demo中，如grpc为   @GRpcService， RSocket RPC为 @RSocketService等

**Comment by foreveryang321** [comment]
赞同。不过这个issue应该到[https://github.com/apache/incubator-dubbo](https://github.com/apache/incubator-dubbo)提比较好吧

**Comment by logyou** [comment]
不能再同意了。

**Comment by ACXNX** [comment]
支持！

**Comment by mail6562** [comment]
这个很早就有人提过了，一直都没改，Service 注解和spring的那个重名

**Comment by mercyblitz** [comment]
Transferring to https://github.com/apache/dubbo/issues/6007.
