### ISSUE TITLE
shiro的realm实现中应用dubbo的调用，导致自定义filter无效

### ISSUE THREAD

**Issue by penweizgx** [apache/dubbo-spring-boot-project#486]
### Environment

* Dubbo version: 2.7
* Operating System version: macos 10.13.6 
* Java version: 1.8

### Steps to reproduce this issue
![image](https://user-images.githubusercontent.com/6983487/55667776-73ef2500-5893-11e9-87f9-7b19d40167c3.png)
![image](https://user-images.githubusercontent.com/6983487/55667785-8e290300-5893-11e9-97f1-e6cd187f9c66.png)

1. consumer 端配置的filter无效，provider端配置的filter正常有效，服务可以正常调用

**Comment by penweizgx** [comment]
经排查，项目权限框架shiro的realm实现类加入了dubbo调用，就会导致自定义filter失效

**Comment by mercyblitz** [comment]
Could you please give me a sample code?
