### ISSUE TITLE
如何指定消费者的IP

### ISSUE THREAD

**Issue by GeXin666** [apache/dubbo-spring-boot-project#492]
dubbo.application.name=dubbo-consumer-demo
dubbo.scan.base-packages=com.pfks.rpc.service

dubbo.protocol.name=dubbo
dubbo.protocol.port=6543
dubbo.registry.address=zookeeper://192.168.80.112:2181
dubbo.protocol.host=192.168.80.1

我的机器有俩快网卡，192.168.80.1和192.168.10.1
它总是用192.168.10.1去连接，但是我的生产者在80网段，如何设置才能让它用80.1的IP去连接

**Comment by mercyblitz** [comment]
You could add the VM options `-DDUBBO_IP_TO_BIND=192.168.80.1` or  `-Ddubbo.network.interface.preferred=${some-network-interface-name}`.
