### ISSUE TITLE
[Issue] Dubbo Spring Boot 2.7.1 PropertyResolver Beans conflict in Spring Boot, ref #459

### ISSUE THREAD

**Issue by zhouzhihua** [apache/dubbo-spring-boot-project#496]
env:
dubbo2.7.1
dubbo-spring-boot2.7.1

error:
***************************
APPLICATION FAILED TO START
***************************

Description:

Field propertyResolver in org.springframework.cloud.netflix.eureka.EurekaClientConfigBean required a single bean, but 2 were found:
	- dubboScanBasePackagesPropertyResolver: defined by method 'dubboScanBasePackagesPropertyResolver' in class path resource [org/apache/dubbo/spring/boot/autoconfigure/DubboRelaxedBindingAutoConfiguration.class]
	- environment: a programmatically registered singleton

**Comment by zhouzhihua** [comment]
There is no need to add dubboScanBasePackagesPropertyResolver to bean context, new a instance will be ok.

**Comment by mercyblitz** [comment]
> There is no need to add dubboScanBasePackagesPropertyResolver to bean context, new a instance will be ok.

Thanks for your reporting issue, this one is a known bug. You could reference this bugfix code: https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/autoconfigure/DubboServiceAutoConfiguration.java#L68

There are two imcompatiable implementations of Relaxed binding between Spring Boot 1.x and 2.x, thus the current implementation uses override bean definition to resolve the difference. Next release will switch SPI to resolve this issue, thank you again!

**Comment by Ariel827** [comment]
> https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/autoconfigure/DubboServiceAutoConfiguration.java#L68

The same problem happened for me.
this link cannot access! Can you update it?
