### ISSUE TITLE
dubbo网关选择或者说如何实现

### ISSUE THREAD

**Issue by 1076572358** [apache/dubbo-spring-boot-project#517]
现在我已经搭建了几个dubbo服务，但是在不同机器上，缺少统一的入口，关于网关这块有什么集成或者实现吗

**Comment by mercyblitz** [comment]
You may wait for Dubbo 2.7.3 release, it will provide more convenient for the implementation of Gateway

**Comment by 1076572358** [comment]
> You may wait for Dubbo 2.7.3 release, it will provide more convenient for the implementation of Gateway

thanks，Is this inside information?Where is the gateway-related message?

**Comment by CodingSinger** [comment]
网关有选择了吗

**Comment by mercyblitz** [comment]
Here is a demo to build a gateway powered by Apache Dubbo
