### ISSUE TITLE
@Reference（registry="test1"） 中注册的不是当前test1，而是默认的test

### ISSUE THREAD

**Issue by ruyuhi** [apache/dubbo-spring-boot-project#524]
我遇到的问题是，本地环境需要调用，本地的dubbo 服务，同时有些功能又得调用测试环境的dubbo服务，所以 我的config 会初始化2个registry, 如下，`
@bean("registryConfig")
public RegistryConfig registryConfig() {
RegistryConfig registryConfig = new RegistryConfig();
registryConfig.setDefault(true);
registryConfig.setAddress(registryAddress);
return registryConfig;
}

@Bean("testRegistry")
public RegistryConfig registryConfigTest() {
	RegistryConfig registryConfig = new RegistryConfig();
	registryConfig.setDefault(false);
	registryConfig.setAddress(registryAddressTest);
	return registryConfig;
}`
然后代码中注入通过 @Reference(registry = "testRegistry", consumer = BaseConstants.DUBBO_CONSUMER_CONFIG_SAAS) private TenantFacade tenantFacade;

发现 tenantFacade 中生效的一直是 registryConfig ，而不是 testRegistry。最后查看了 ReferenceBean.class 的afterPropertiesSet 方法 源码，发现在初始化时，只会采用默认的和没有设置false的，代码如下：
if ((getRegistries() == null || getRegistries().isEmpty()) && (getConsumer() == null || getConsumer().getRegistries() == null || getConsumer().getRegistries().isEmpty()) && (getApplication() == null || getApplication().getRegistries() == null || getApplication().getRegistries().isEmpty())) { Map<String, RegistryConfig> registryConfigMap = applicationContext == null ? null : BeanFactoryUtils.beansOfTypeIncludingAncestors(applicationContext, RegistryConfig.class, false, false); if (registryConfigMap != null && registryConfigMap.size() > 0) { List<RegistryConfig> registryConfigs = new ArrayList<RegistryConfig>(); for (RegistryConfig config : registryConfigMap.values()) { if (config.isDefault() == null || config.isDefault().booleanValue()) { registryConfigs.add(config); } } if (registryConfigs != null && !registryConfigs.isEmpty()) { super.setRegistries(registryConfigs); } } }

，我如果要调用不同环境下的dubbo 服务，用@reference 注解怎么实现呢

**Comment by mercyblitz** [comment]
Did you use the XML configuration?
