### ISSUE TITLE
Field propertyResolver in org.springframework.cloud.netflix.eureka.EurekaClientConfigBean required a single bean

### ISSUE THREAD

**Issue by zondahuman** [apache/dubbo-spring-boot-project#525]
<dubbo.version>2.7.1</dubbo.version>
 

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>${dubbo.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-dependencies-bom</artifactId>
            <version>${dubbo.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.7.1</version>
        </dependency>

错误异常：
Field propertyResolver in org.springframework.cloud.netflix.eureka.EurekaClientConfigBean required a single bean, but 2 were found:
	- dubboScanBasePackagesPropertyResolver: defined by method 'dubboScanBasePackagesPropertyResolver' in class path resource [org/apache/dubbo/spring/boot/autoconfigure/DubboRelaxedBinding2AutoConfiguration.class]
	- environment: a programmatically registered singleton

why?

**Comment by mercyblitz** [comment]
Please refer to https://github.com/apache/dubbo-spring-boot-project/issues/496
