### ISSUE TITLE
When will version 2.7.2 be released?

### ISSUE THREAD

**Issue by fangQiangQiang** [apache/dubbo-spring-boot-project#527]
When will version 2.7.2 be released?

**Comment by rxxy** [comment]
urgent need

**Comment by mercyblitz** [comment]
It will issue a release vote this week

**Comment by CrisLi** [comment]
Is there anywhere we can see the vote progress?

**Comment by fuyongde** [comment]
> Is there anywhere we can see the vote progress?

https://github.com/apache/dubbo-spring-boot-project/milestone/6
