### ISSUE TITLE
dubbo服务 nacos 命名空间无法使用指定的

### ISSUE THREAD

**Issue by RongXiong2016** [apache/dubbo-spring-boot-project#530]
spring-boot项目 yml配置文件如下
dubbo:
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}
  protocol:
    port: -1
    name: dubbo
  provider:
    timeout: 60000
    retries: 0
  config-center:
    namespace: 8ef585bb-44d7-4774-b65b-ff3f0b2fd4e1

nacos:
  server-address: 127.0.0.1
  port: 8848

在nacos上新建了一个命名空间 服务重新启动后还是注册到了默认的命名空间，是还有哪个地方没有配置到吗

**Comment by jeck5001** [comment]
Duplicate of #460 好像现在还不支持

**Comment by bigbluecat** [comment]
有支持计划么？

**Comment by mercyblitz** [comment]
You should add the namespace as the  parameter of URL in the registry, like this :

Origin:

```
dubbo. registry.address =  nacos://${nacos.server-address}:${nacos.port}
```

After: 

```
dubbo. registry.address =  nacos://${nacos.server-address}:${nacos.port}?namespaace=xxx
```

**Comment by RongXiong2016** [comment]
now i need register different namespaces with nacos.
nacos is cluster
