### ISSUE TITLE
请问dubbo在springboot上支持的全部配置去哪看？

### ISSUE THREAD

**Issue by wlaini520520** [apache/dubbo-spring-boot-project#538]

**Comment by fuyongde** [comment]
引入`dubbo-spring-boot-starter`的依赖后，有一个`dubbo-spring-boot-autoconfigure-compatible-2.7.1.jar`，这个jar里面`/META-INF/spring-configuration-metadata.json`文件就是全部的配置项

**Comment by wlaini520520** [comment]
好的，万分感谢^_^o ~~~
