### ISSUE TITLE
[Bug] Maven CI Friendly multimode fast dependency error

### ISSUE THREAD

**Issue by zhangfei9734** [apache/dubbo-spring-boot-project#539]
- [x] I have searched the [issues](https://github.com/apache/dubbo-spring-boot-project/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.2
* Dubbo Spring Boot version: 2.7.1
* Operating System version: Linux runner***** SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 GNU/Linux
* Java version: 1.8.0_212

### Steps to reproduce this issue

```xml
<groupId>com.aliyun.app</groupId>
<artifactId>demo</artifactId>
<version>${revision}</version>

<properties>
  <revision>0.0.1-SNAPSHOT</revision>
</properties>
// ...

    <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo-spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo-dependencies-zookeeper</artifactId>
      <type>pom</type>
    </dependency>
```

```bash
mvn -T 4C -U -B -Drevision=${BUILD_VERSION} -Dmaven.test.skip=${MAVEN_TEST_SKIP} -Djava.net.preferIPv4Stack=true -Ddebug=false clean package
```

[Maven CI Friendly#Dependencies](https://maven.apache.org/maven-ci-friendly.html#Dependencies)
![image](https://user-images.githubusercontent.com/16345433/60793530-731fa500-a19a-11e9-9909-fca08a354f9a.png)

- https://github.com/apache/dubbo-spring-boot-project/blob/a2312769202cd294e510e6f5b2ffad70cc20d924/dubbo-spring-boot-parent/pom.xml#L42 
- https://github.com/apache/dubbo-spring-boot-project/blob/a2312769202cd294e510e6f5b2ffad70cc20d924/dubbo-spring-boot-actuator/pom.xml#L64
- https://github.com/apache/dubbo-spring-boot-project/blob/a2312769202cd294e510e6f5b2ffad70cc20d924/dubbo-spring-boot-compatible/actuator/pom.xml#L64
- ...

### Expected Result

Build success.

### Actual Result
```bash
[ERROR] Failed to execute goal on project aliyun-dubbo: Could not resolve dependencies for project com.aliyun.app:demo-dubbo:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.apache.dubbo:dubbo-spring-boot-starter:jar:2.7.1: Failed to read artifact descriptor for org.apache.dubbo:dubbo-spring-boot-starter:jar:2.7.1: Could not transfer artifact org.apache.dubbo:dubbo-dependencies-bom:pom:1.0.0-SNAPSHOT from/to aliyun.central (https://maven.aliyun.com/repository/public/): Not authorized -> [Help 1]
```

**Comment by mercyblitz** [comment]
Please use Maven 3.5.0 and above~
