### ISSUE TITLE
建议dubbo-spring-boot-starter和dubbo的版本可以同步

### ISSUE THREAD

**Issue by Shiyajian** [apache/dubbo-spring-boot-project#543]
dubbo 已经2.7.2.release了，马上要发布2.7.3了，starter的最高版本还是2.7.1。这样我关于dubbo就需要维护2个版本号，实在不方便。建议dubbo和starter的版本可以同步发行

**Comment by mercyblitz** [comment]
Good suggestion.

**Comment by mercyblitz** [comment]
#554
