### ISSUE TITLE
springboot1.5.8 dubbo-spring-boot-starter1.0.0配置集群启动报错

### ISSUE THREAD

**Issue by dzf123** [apache/dubbo-spring-boot-project#549]
config;
spring.dubbo.registry.address=127.0.0.1:2182|127.0.0.1:2183|127.0.0.1:2184
spring.dubbo.registry.protocol=zookeeper
spring.dubbo.server=true
spring.dubbo.protocol=dubbo

error:
Caused by: java.net.ConnectException: Connection refused: no further information

**Comment by mercyblitz** [comment]
It's a no official starter, please use https://github.com/apache/dubbo-spring-boot-project/releases/tag/2.7.1 or https://github.com/apache/dubbo-spring-boot-project/releases/tag/0.1.1
