### ISSUE TITLE
springboot 泛化调用的时候能不能也用@Reference引用一个远程的服务？

### ISSUE THREAD

**Issue by CodingSinger** [apache/dubbo-spring-boot-project#552]
如题。
好像现在没这个实现，但是感觉如下方案可以实现？
```java
@Reference(interfaceName="com.xxx.xxx.DemoService",generic="true")
GenericService genericService;
```
解析的时候如果指定了是泛化，则设置interfacename为注解中interfaceName的值，如果没指定泛化为true，则走原来的步骤。

**Comment by CodingSinger** [comment]
@mercyblitz

**Comment by mercyblitz** [comment]
Good idea, it should be a Dubbo feature, see https://github.com/apache/dubbo/issues/4594

**Comment by CodingSinger** [comment]
can i commit a pr to this?
