### ISSUE TITLE
The default property value of spring boot should not be modified

### ISSUE THREAD

**Issue by brucelwl** [apache/dubbo-spring-boot-project#556]
property  of `spring.main.allow-bean-definition-overriding`  in spring boot default value is false,`dubbo-spring-boot-project` should not modify it, it should be decided by the developer himself. Otherwise, the developer's program may produce unexpected exceptions. see `org.apache.dubbo.spring.boot.env.DubboDefaultPropertiesEnvironmentPostProcessor`

使用Spring条件注解可以解决问题
```
com.alibaba.boot.dubbo.autoconfigure.DubboAutoConfiguration
 @ConditionalOnProperty(name = MULTIPLE_CONFIG_PROPERTY_NAME, havingValue = "false",matchIfMissing = true)
 @EnableDubboConfig
 protected static class SingleDubboConfigConfiguration {
 
 }

```

**Comment by mercyblitz** [comment]
Not just for this problem, If there are two annotated `@EnableDubboConfig` Configuration classes, it also raises a Exception

**Comment by mercyblitz** [comment]
Raise a new issue in dubbo https://github.com/apache/dubbo/issues/4690
