### ISSUE TITLE
When I use sub-package named 'impl' for provider services, then dubbo will ignore them, even though I annotate with dubbo @Service.

### ISSUE THREAD

**Issue by leonard99559** [apache/dubbo-spring-boot-project#559]
My provider module directory structure like below :
- com.xxx
   - demo.impl
        - DemoServiceImpl.java

In DemoServiceImpl.java, I annotate dubbo's @Service on the class, and start the module.
Then the service can't be registered on zookeeper.

But when I change the structure like below, it goes fine.
- com.xxx
   - demo.provider
        - DemoServiceImpl.java

**Comment by mercyblitz** [comment]
You'd better to change the base-packages in `@DubboComponentScan`.

**Comment by leonard99559** [comment]
In application.properties, I have set the property : dubbo.xxx.base-package.
 If to use @DubboComponentScan, is it duplicated configuration?

**Comment by leonard99559** [comment]
Close the issue, for it does not occur again.
