### ISSUE TITLE
con't inject spring bean in dubbo @Service class

### ISSUE THREAD

**Issue by RojerAlone** [apache/dubbo-spring-boot-project#568]
I use the latest version of dubbo-spring-boot, the commit hash is c585d2df619c26da29e6a29f9ae7c27576c593b0，and I use the 2.7.3 tag to test again.

I found that con't inject spring bean by @Autowired annotation in provider class which is annotated by @Service, I only edit the code like below:
![image](https://user-images.githubusercontent.com/20370513/62357717-3f8c2c80-b546-11e9-837e-26ef19e634a5.png)
and I got error log like this:
```java
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-08-02 16:57:56.367 ERROR 25746 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field test in org.apache.dubbo.spring.boot.demo.provider.service.DefaultDemoService required a bean of type 'org.apache.dubbo.spring.boot.demo.provider.service.Test' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


Action:

Consider defining a bean of type 'org.apache.dubbo.spring.boot.demo.provider.service.Test' in your configuration.
```
It looks like dubbo scan its beans before spring itself, is there some incorrect configuration I did?

**Comment by RojerAlone** [comment]
I solved it by add `@Lazy` annotation on the spring bean, is it a defect of design?

**Comment by tswstarplanet** [comment]
It's because you didn't configure the component scan packages. You can configure like this

![dubbo-spring-boot-issue-568](https://user-images.githubusercontent.com/3047563/62730616-eabf4900-ba52-11e9-97fb-71ef446a4f42.jpeg)

**Comment by tswstarplanet** [comment]
But I added the @Lazy annotation to the bean, but didn't add the component scan packages, it didn't work.

**Comment by RojerAlone** [comment]
> But I added the @lazy annotation to the bean without adding the component scan packages, it didn't work.

Maybe your bootstrap class is not under the root package?

@tswstarplanet You remind me, I use `@EnableAutoConfiguration` instead of `@SpringBootApplication` for some reason before.

Now I use `@SpringBootApplication` on my bootstrap class, `@Service` annotation works without `@Lazy`.

Sorry, it's my problem. And thanks a lot.
