### ISSUE TITLE
spring版本冲突 java.lang.AbstractMethodError: org.springframework.boot.context.config.ConfigFileApplicationListener.supportsSourceType(Ljava/lang/Class;)Z

### ISSUE THREAD

**Issue by 5kywa1ker** [apache/dubbo-spring-boot-project#570]
spring boot 版本 2.1.4.RELEASE
dubbo 版本 2.6.5
spring cloud 版本 Greenwich.SR1
dubbo-dependencies-bom中的<spring_version>4.3.16.RELEASE</spring_version> 而 spring boot中的spring version 是5.1.6.RELEASE
启动直接报错
![image](https://user-images.githubusercontent.com/11732424/62407434-0eb20300-b5eb-11e9-8fd1-76ad3d4fbf26.png)

**Comment by 5kywa1ker** [comment]
已解决

**Comment by shuaicj** [comment]
@5kywa1ker 请问如何解决的，是降级spring-boot版本，还是在dubbo中exclude spring-context?

**Comment by 5kywa1ker** [comment]
> @5kywa1ker 请问如何解决的，是降级spring-boot版本，还是在dubbo中exclude spring-context?

在dependencyManagement中引入spring-boot-starter-parent的pom依赖，项目不要从spring-boot-starter-parent继承。dependencyManagement里面的pom中版本的优先级比parent继承的优先级高。
