### ISSUE TITLE
最新版本的2.7.3在maven仓库中不能下载？

### ISSUE THREAD

**Issue by zjw2011** [apache/dubbo-spring-boot-project#575]
最新版本的2.7.3在maven仓库中不能下载？

**Comment by fuyongde** [comment]
> 最新版本的2.7.3在maven仓库中不能下载？

现在还是Pre-Release阶段

**Comment by mostcool** [comment]
> > 最新版本的2.7.3在maven仓库中不能下载？
> 
> 现在还是Pre-Release阶段

太慢了，dubbo-2.7.3 都发布半个月了。这还没跟上。

**Comment by liuminda** [comment]
> > > 最新版本的2.7.3在maven仓库中不能下载？
> > 
> > 
> > 现在还是Pre-Release阶段
> 
> 太慢了，dubbo-2.7.3 都发布半个月了。这还没跟上。

耐心点  慢工出细活

**Comment by mercyblitz** [comment]
> > > 最新版本的2.7.3在maven仓库中不能下载？
> > 
> > 
> > 现在还是Pre-Release阶段
> 
> 太慢了，dubbo-2.7.3 都发布半个月了。这还没跟上。

Sorry for the delayed release, one main reason is that Apache Dubbo release process has to issue the vote, like this:

![image](https://user-images.githubusercontent.com/533114/63067694-bf50c880-bf42-11e9-8525-57c8c5fad83a.png)

It costs 72 hours(3 days) for every vote at least, and it's hard to be approved in the first vote.

> The prepare for release  - https://dubbo.apache.org/zh-cn/blog/prepare-an-apache-release.html
