### ISSUE TITLE
dubbo+shiro整合 realm类调用dubbo方法出错

### ISSUE THREAD

**Issue by GodIsMadao** [apache/dubbo-spring-boot-project#576]
1.realm类里面reference调用dubbo的service方法，然后导致一直在请求::9090，报错
![image](https://user-images.githubusercontent.com/13927602/62757362-a8772580-baad-11e9-9a0a-0719e3da4039.png)
2.如果去掉了@Reference注解，可以运行起来，但是貌似filter不起作用了

**Comment by GodIsMadao** [comment]
把shiro配置去掉就可以正常运行

**Comment by mercyblitz** [comment]
It's seen that it's no Dubbo issue
