### ISSUE TITLE
Why is there no version of Dubbo Spring Boot 2.7.2?

### ISSUE THREAD

**Issue by colove** [apache/dubbo-spring-boot-project#577]
When I saw the released version，I didn't find the version of Dubbo Spring Boot 2.7.2.   If I use the 
Dubbo 2.7.2 or 2.7.3, whether this is fully compatible with this version or not?

**Comment by RojerAlone** [comment]
I use Dubbo 2.7.2 and Dubbo Spring Boot 2.7.1, it works well.
And I'm waiting for Dubbo Spring Boot 2.7.3, too, the release vote has been passed (I see it in dubbo mailing list), it will release soon.

**Comment by mercyblitz** [comment]
Since Dubbo 2.7.2 is a unstable version, please upgrade 2.7.3 and its Spring Boot starter.
