### ISSUE TITLE
Is it appropriate about the suffix of ServiceAnnotationBeanPostProcessor class name?

### ISSUE THREAD

**Issue by DavidLea99** [apache/dubbo-spring-boot-project#582]
I find a small flaw about the name of ServiceAnnotationBeanPostProcessor. The class ServiceAnnotationBeanPostProcessor is actually an implementation of BeanFactoryPostProcessor instead of BeanPostProcessor, but the name looks like an implementation of the BeanPostProcessor interface.

**Comment by mercyblitz** [comment]
Good advice, it may be renamed in a future release.

Please trace the issue : https://github.com/apache/dubbo/issues/4830

**Comment by DavidLea99** [comment]
OK, thx!
