### ISSUE TITLE
注册Filter的Eeception 被spring的DataBuilder默认的ErrorProcessor 吃掉了没有抛出和处理

### ISSUE THREAD

**Issue by ShenFeng312** [apache/dubbo-spring-boot-project#593]
注册Filter时 如果filter没有加在org.apache.dubbo.rpc.Filter 目录下回抛出  new IllegalStateException("No such extension " + v + " for " + property + "/" + type.getName()) 但是这个好像被springDataBinder 默认的ErrorProcessor 给吃掉了 导致报错没有反馈到用户应该添加一个自定义的ErrorProcessor 解决这个问题

**Comment by mercyblitz** [comment]
Please report this issue to apache/dubbo, thanks~
