### ISSUE TITLE
 springboot  可以同时 支持rest 和dubbo 两种协议？

### ISSUE THREAD

**Issue by mail6562** [apache/dubbo-spring-boot-project#596]
配置同时支持rest 和dubbo协议。启动没有问题。但是调用接口不通：
配置文件：
`spring:
  application:
    name: dubbo-registry-nacos-provider-sample
demo:
  service:
    version: 1.0.0
nacos:
  host: 192.168.4.50
  port: 8848
dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}
  protocols:
    - id: dubbo
      name: dubbo
      port : -1
      server: netty
    - id: rest
      name: rest
      port: 8080
      server: netty
`
接口：
public interface DemoService {

    String sayHello(String name);

}
接口实现：
@Path("users")
@Consumes({MediaType.APPLICATION_JSON, MediaType.TEXT_XML})
@Produces({MediaType.APPLICATION_JSON, MediaType.TEXT_XML})
@Service(version = "${demo.service.version}")
public class DefaultDemoService implements DemoService {
    @Value("${dubbo.application.name}")
    private String serviceName;
    @GET
    @Path("test")
    @Override
    public String sayHello(String name) {
        return String.format("[%s] : Hello 333333333, %s", serviceName);
    }
}
rest 请求的包引用参考：
 http://dubbo.apache.org/zh-cn/blog/dubbo-rest.html 
启动类：
@EnableAutoConfiguration
public class DubboRegistryNacosProviderBootstrap {

    public static void main(String[] args) {
        new SpringApplicationBuilder(DubboRegistryNacosProviderBootstrap.class)
                .run(args);
    }
}

服务正常启动。配置两种协议后，rest调用 404， dubbo 客户端启动也会出错。注册中心是nacos

**Comment by mercyblitz** [comment]
It works, how about your code?
