### ISSUE TITLE
服务配置细节优化建议

### ISSUE THREAD

**Issue by shenliuyang** [apache/dubbo-spring-boot-project#597]
可否把version等一些可以暴露给consumer的配置已注解的形势配在interface上。 这样免去了consumer端对应依赖服务升级时需知道服务provider具体升级到了那个版本。
@Reference 如果不指定version 那就默认使用对应接口上注解version。  更加便利了。

**Comment by mercyblitz** [comment]
It's hard to implement this requirement, for now on, the interface can be annotated by `@Service`, however, `@Service` supports placeholder for version and group attributes, thus, the consumer still does not know which version or group that the provider declares.
