### ISSUE TITLE
紧急求助，怎么在消费端配置多个zookeeper注册中心？总是报No registry config found or it's not a valid config

### ISSUE THREAD

**Issue by huzhenpengssp** [apache/dubbo-spring-boot-project#598]
我使用dubbo-spring-boot-starter 2.7.3，在application.properties配置了多个zookeeper注册中心，然后就一直报错No registry config found or it's not a valid config。
我的配置是：

dubbo.registrys.cot1.address=zookeeper://127.0.0.1:2181
dubbo.registrys.cot1.address=zookeeper://127.0.0.1:2182

紧急求助

**Comment by shenliuyang** [comment]
仔细看下这个类(DubboConfigConfiguration)里面的 Multiple.  你就知道怎么配置多个注册中心了

**Comment by mercyblitz** [comment]
```properties
dubbo.registrys.cot1.address=zookeeper://127.0.0.1:2181
dubbo.registrys.cot1.address=zookeeper://127.0.0.1:2182 // cot1 is a duplicated one, please rename it
```
