### ISSUE TITLE
直连无法进行版本控制

### ISSUE THREAD

**Issue by hqxy** [apache/dubbo-spring-boot-project#602]
环境
dubbo-spring-boot-starter 版本：2.7.3
操作系统：win10
java: 8
问题描述：
当不设置注册中心,直接指定url调用时，会报找不到远程调用的错误，客户端版本号始终为0.0.0
debug了一下dubbo的代码，发现在org.apache.dubbo.rpc.cluster.support.ClusterUtils#mergeUrl方法将version给remove
org.apache.dubbo.rpc.cluster.support.ClusterUtils#mergeUrl  87行

**Comment by mercyblitz** [comment]
It's a known issue, it will be fixed in 2.7.4
