### ISSUE TITLE
异步调用问题-2.7.3

### ISSUE THREAD

**Issue by 1996-gjq** [apache/dubbo-spring-boot-project#606]
//1.
@Reference(version = "1.0" ,methods = {@Method(name = "say",async = true)})
 SayHello sayHello;
 public String hello(){
        sayHello.say();
}
为什么调用say()方法时还是阻塞的?是我配置的问题吗?
//2.
@Reference(version = "1.0" ,methods = {@Method(name = "say",async = true)},async = true)
 SayHello sayHello;
 public String hello(){
        sayHello.say();
}
如果这样配置所有方法都成了异步的?不能指定单个方法吗?

**Comment by 1996-gjq** [comment]
2.7.3版本

**Comment by 1996-gjq** [comment]
很难用,不纠结了.
我还是用jdk的Future吧.
问题先挂这儿,有知道的大佬麻烦帮忙解答下,不胜感激!

**Comment by mercyblitz** [comment]
It's considered to support the method-level annotation `@Method`

**Comment by 1996-gjq** [comment]
> It's considered to support the method-level annotation `@Method`
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.ANNOTATION_TYPE})
@Inherited
public @interface Method {
}
This is Annotation type declaration.
