### ISSUE TITLE
[Notification] About Dubbo Spring Boot 2.7.4 release plan

### ISSUE THREAD

**Issue by mercyblitz** [apache/dubbo-spring-boot-project#607]
It's a plan that Dubbo Spring Boot 2.7.4 will be released in next week, it's waiting for the release of Dubbo 2.7.4 .

**Comment by wangweiweiwei** [comment]
所以是下周发布吗10-14至10-18?

**Comment by dangit815** [comment]
Can we support Dubbo 2.7.4 this week?

**Comment by emacsist** [comment]
dubbo 2.7.4 已经发布. 不知道什么时候更新?

**Comment by mercyblitz** [comment]
> dubbo 2.7.4 已经发布. 不知道什么时候更新?

It's waiting for new bug-fixed 2.7.4.1

**Comment by mercyblitz** [comment]
2.7.4.1 : https://github.com/apache/dubbo/issues/5219

**Comment by itlihuaxin** [comment]
Can we support Dubbo 2.7.4.1 this week?

**Comment by makingtime** [comment]
it's stll 2.7.3 in maven central repo: https://search.maven.org/artifact/org.apache.dubbo/dubbo-spring-boot-starter/2.7.3/jar

**Comment by arthur657834** [comment]
it's stll 2.7.3 
https://mvnrepository.com/artifact/org.apache.dubbo/dubbo-spring-boot-starter

**Comment by mostcool** [comment]
Has the vote for version 2.7.4.1 been over?
When is it released?
This is too slow...

**Comment by mercyblitz** [comment]
The vote email: https://lists.apache.org/thread.html/73980c91e207b244342fd77b792bfda65c9e7434bfa048e70f490f8a@%3Cdev.dubbo.apache.org%3E

Thanks for the long long wait.
