### ISSUE TITLE
使用 @Reference 指定version不生效默认是 0.0.0 

### ISSUE THREAD

**Issue by czbabl** [apache/dubbo-spring-boot-project#613]
client:
    @Reference(version = "1.0.0",url = "dubbo://127.0.0.1:12345")
    private IDefaultDemoService demoService;

error:
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Oct 14 10:09:42 CST 2019
There was an unexpected error (type=Internal Server Error, status=500).
Failed to invoke remote method: sayHello, provider: dubbo://127.0.0.1:12345/com.cz.dubbo.demo.service.IDefaultDemoService?application=dubbo-consumer-demo&interface=com.cz.dubbo.demo.service.IDefaultDemoService&lazy=false&pid=12008&qos.enable=false&register.ip=172.24.239.33&remote.application=&revision=1.0.0&side=consumer&sticky=false, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: com.cz.dubbo.demo.service.IDefaultDemoService:12345 in [com.cz.dubbo.demo.service.IDefaultDemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /172.24.239.33:52132 --> provider: /172.24.239.33:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[callback messsage is :cz], attachments={path=com.cz.dubbo.demo.service.IDefaultDemoService, input=253, dubbo=2.0.2, interface=com.cz.dubbo.demo.service.IDefaultDemoService, version=0.0.0}] org.apache.dubbo.remoting.RemotingException: Not found exported service: com.cz.dubbo.demo.service.IDefaultDemoService:12345 in [com.cz.dubbo.demo.service.IDefaultDemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /172.24.239.33:52132 --> provider: /172.24.239.33:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[callback messsage is :cz], attachments={path=com.cz.dubbo.demo.service.IDefaultDemoService, input=253, dubbo=2.0.2, interface=com.cz.dubbo.demo.service.IDefaultDemoService, version=0.0.0}] at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:266) at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:127) at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102) at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193) at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

server:
package com.cz.dubbo.demo.service;

import org.apache.dubbo.config.annotation.Service;
import org.springframework.beans.factory.annotation.Value;

@Service(version = "1.0.0")
public class DefaultDemoService implements IDefaultDemoService{

    @Value("${dubbo.application.name}")
    private String serviceName;

    public String sayHello(String name){
        return serviceName;
    }
}

1.去除@Reference中url = "dubbo://127.0.0.1:12345" ，@Reference中version生效
2.去除server端中的版本1.0.0 ，客户端也没问题

引用的是最新的版本

**Comment by DoyleCzh** [comment]
遇到了同样的问题，@Reference 中使用version无法生效

**Comment by sonymoon** [comment]
What registry was used in this case?

**Comment by wzqiang1332** [comment]
sample demo version不起作用，zk的demo没问题

**Comment by mercyblitz** [comment]
> version

It's a known issue, will be resolved in new release

**Comment by ehlxr** [comment]
2.7.6 版本还是有问题
