### ISSUE TITLE
2.7.3 transaction is error

### ISSUE THREAD

**Issue by l343765828** [apache/dubbo-spring-boot-project#617]
@Override
    @Transactional(rollbackFor = Exception.class)
    public String sayHello(String name) {
        var a=UUID.randomUUID().toString().replaceAll("-","");
        tmapper.ins(a);
        var b=1/0;
        return a;
    }
dubbo'service transaction isn't roll，the data insert database
2.7.1 is ok

**Comment by l343765828** [comment]
@mercyblitz

**Comment by mercyblitz** [comment]
Can you try to use 2.7.4.1?

**Comment by l343765828** [comment]
no I used 2.7.3

**Comment by mercyblitz** [comment]
Did you use an annotation `@Reference` injecting a local Service Bean? If you did, please switch it to be `@Autowired`, or wait for 2.7.6 release

**Comment by l343765828** [comment]
thank you itry it
