### ISSUE TITLE
dubbo Endpoint 为啥没有抽象 receive 方法？

### ISSUE THREAD

**Issue by xiaoheng1** [apache/dubbo-spring-boot-project#621]
我使用的是 dubbo2.7.1

1.在看 Endpint 接口的时候，发现只抽象了 send 方法，为啥没有抽象 receive 用于接收数据了？

2.Endpoint 接口的 send 方法和 ChannelHandler 接口中的 sent 方法的区别和联系是啥样的了？

**Comment by zhaizhengqing** [comment]
@xiaoheng1 
First please communicate in English, not all maintainers can read Chinese.
Second give out your opinion or suggestion directly like what we should do, not asking why we did or not did.

**Comment by mercyblitz** [comment]
Please report this issue to https://github.com/apache/dubbo, thanks~
