### ISSUE TITLE
Is the multiple registry configuration prefix dubbo.registrys or dubbo.registries?

### ISSUE THREAD

**Issue by liunancun** [apache/dubbo-spring-boot-project#622]
Is the multiple registry configuration prefix dubbo.registrys or dubbo.registries?

use:
dubbo.registrys.one.address=nacos://192.168.99.237:8848
dubbo.registrys.two.address=nacos://localhost:8848

Start error:
java.lang.IllegalStateException: No registry config found or it's not a valid config! The registry config is: <dubbo:registry valid="false" zookeeperProtocol="false" prefix="dubbo.registry" />

use:
dubbo.registries.one.address=nacos://192.168.99.237:8848
dubbo.registries.two.address=nacos://localhost:8848

Successful startup

But Spring Boot configuration file warning:
'dubbo.registries.one.address' is an unknown property.

**Comment by mercyblitz** [comment]
`dubbo.registries` is the valid prefix for the multiple RegistryConfig binding.
