### ISSUE TITLE
关于@Service注释的一点建议

### ISSUE THREAD

**Issue by uniorder** [apache/dubbo-spring-boot-project#628]
能否将Dubbo的Service注解与Spring自带的Spring注解区分开来？因为如果两个注解都使用的话可能会比较怪异：

```java
@Service
@Slf4j
@com.alibaba.dubbo.config.annotation.Service(interfaceClass = AddressApi.class)
public class AddressService implements AddressApi
```

**Comment by minatoyukina** [comment]
@uniorder you can simply replace spring Service with Component

**Comment by itlihuaxin** [comment]
只使用org.apache.dubbo.config.annotation.Service本身也可以注册成bean，@Autowired也可以引用到

**Comment by mercyblitz** [comment]
Dubbo's @Service is a legacy annotation, there are many applications using it, it's hard to refactor or rename it.
