### ISSUE TITLE
 zookeeper not connected

### ISSUE THREAD

**Issue by itlihuaxin** [apache/dubbo-spring-boot-project#630]
版本信息：zookeeper-3.4.14， dubbo 2.7.4.1
application.properties: dubbo.registry.address=zookeeper://xxx:2181
报错的地方
public ZookeeperClient createZookeeperClient(URL url) {
        return new CuratorZookeeperClient(url);
    }
url为
zookeeper://xxxx:2181/ConfigCenterConfig?check=true&config-file=dubbo.properties&group=dubbo&highest-priority=false&namespace=dubbo&timeout=3000

dubbo 2.7.3就没有这个问题

**Comment by itlihuaxin** [comment]
dubbo 2.7.3的URL是这个zookeeper://xxx:2181/org.apache.dubbo.remoting.zookeeper.ZookeeperTransporter

**Comment by itlihuaxin** [comment]
2.7.4.1多了这个org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient
boolean connected = client.blockUntilConnected(timeout, TimeUnit.MILLISECONDS);
            if (!connected) {
                throw new IllegalStateException("zookeeper not connected");
            }

**Comment by mercyblitz** [comment]
Fixed
