### ISSUE TITLE
使用@Reference报错 springcloud跑不起来 注释掉之后就能跑起来

### ISSUE THREAD

**Issue by co1d** [apache/dubbo-spring-boot-project#632]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testController': Injection of @Reference dependencies is failed; nested exception is java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.RegistryFactory by name spring-cloud

**Comment by mercyblitz** [comment]
Please use spring-cloud-alibaba-dubbo as a module from https://github.com/alibaba/spring-cloud-alibaba
