### ISSUE TITLE
升级 dubbo 2.7.5 版本时，以下依赖包同样需要升级。

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-spring-boot-project#633]
java.lang.NoClassDefFoundError: org/apache/dubbo/config/spring/util/BeanRegistrar
6a05d3>         at org.apache.dubbo.spring.boot.beans.factory.config.OverrideBeanDefinitionRegistryPostProcessor.postProcessBeanDefinitionRegistry(OverrideBeanDefinitionRegistryPostProcessor.java:36)
6a05d3>         at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:70)
6a05d3>         at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:691)
6a05d3>         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528)
6a05d3>         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
6a05d3>         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
6a05d3>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
6a05d3>         at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
6a05d3>         at org.dubbo.samples.protostuff.provider.ProviderApp.main(ProviderApp.java:28)
6a05d3> Caused by: java.lang.ClassNotFoundException: org.apache.dubbo.config.spring.util.BeanRegistrar
6a05d3>         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
6a05d3>         at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
6a05d3>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
6a05d3>         at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
6a05d3>         ... 9 common frames omitted

**Comment by iqiancheng** [comment]
怎么升级呢？ 应该升级哪个包？

**Comment by shifefiei** [comment]
怎么升级呢？ 应该升级哪个包？

**Comment by shifefiei** [comment]
> 

直接引入 starter 的 2.7.15 版本
<dependency>
<groupId>org.apache.dubbo</groupId>
<artifactId>dubbo-spring-boot-starter</artifactId>
<version>2.7.15</version>
</dependency>
