### ISSUE TITLE
/dubbo-2.7.3.jar!/org/apache/dubbo  ---- What's the matter with the " ! "

### ISSUE THREAD

**Issue by MarlboBlack** [apache/dubbo-spring-boot-project#641]
I used the official recommended version, but I encountered the following errors。。

Description:

An attempt was made to call the method org.apache.dubbo.config.spring.util.PropertySourcesUtils.getPrefixedProperties(Lorg/springframework/core/env/PropertySources;Ljava/lang/String;)Ljava/util/Map; but it does not exist. Its class, org.apache.dubbo.config.spring.util.PropertySourcesUtils, is available from the following locations:

    jar:file:/C:/Users/Administrator/.m2/repository/org/apache/dubbo/dubbo/2.7.3/dubbo-2.7.3.jar!/org/apache/dubbo/config/spring/util/PropertySourcesUtils.class

It was loaded from the following location:

    file:/C:/Users/Administrator/.m2/repository/org/apache/dubbo/dubbo/2.7.3/dubbo-2.7.3.jar

**Comment by SimpleHello** [comment]
I have the same problem 。。where is the  method

DubboRelaxedBinding2AutoConfiguration # 45 

@Bean(
        name = {"dubboScanBasePackagesPropertyResolver"}
    )
    public PropertyResolver dubboScanBasePackagesPropertyResolver(final ConfigurableEnvironment environment) {
        ConfigurableEnvironment propertyResolver = new AbstractEnvironment() {
            protected void customizePropertySources(MutablePropertySources propertySources) {
                Map<String, Object> dubboScanProperties = **PropertySourcesUtils.getPrefixedProperties**(environment.getPropertySources(), "dubbo.scan.");
                propertySources.addLast(new MapPropertySource("dubboScanProperties", dubboScanProperties));
            }
        };
        ConfigurationPropertySources.attach(propertyResolver);
        return new DelegatingPropertyResolver(propertyResolver);
    }
