### ISSUE TITLE
2.7.5 dubbo-spring-boot-starter

### ISSUE THREAD

**Issue by tonyLee1** [apache/dubbo-spring-boot-project#645]
java.lang.NoClassDefFoundError: org/apache/dubbo/config/spring/util/BeanRegistrar

**Comment by mercyblitz** [comment]
How to reproduce?

**Comment by tonyLee1** [comment]
Upgrade Dubbo version to 2.7.5. The above error occurs when Dubbo spring boot starter version is 2.7.4.1. See the function ID in 2.7.3 is deprecated

**Comment by tonyLee1** [comment]
Upgrade Dubbo version to 2.7.5. The above error occurs when Dubbo spring boot starter version is 2.7.4.1. See the function ID in 2.7.3 is deprecated




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mercy Ma"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月2日(星期四) 上午10:11
收件人:&nbsp;"apache/dubbo-spring-boot-project"<dubbo-spring-boot-project@noreply.github.com&gt;;
抄送:&nbsp;"阿杰"<498959412@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/dubbo-spring-boot-project] 2.7.5 dubbo-spring-boot-starter (#645)




How to reproduce?

**Comment by SimpleHello** [comment]
your dubbo.version must the same with dubbo-spring-boot-starter version
like all 2.7.4.1

**Comment by mercyblitz** [comment]
Released!
