### ISSUE TITLE
${revision} issue for dubbo-spring-boot-parent-2.7.4.1 with maven 3.6.3

### ISSUE THREAD

**Issue by htynkn** [apache/dubbo-spring-boot-project#658]
Refer to https://github.com/apache/dubbo/pull/5570

https://repo1.maven.org/maven2/org/apache/dubbo/dubbo-spring-boot-parent/2.7.4.1/dubbo-spring-boot-parent-2.7.4.1.pom

![image](https://user-images.githubusercontent.com/659135/72048789-869dfb00-32f8-11ea-9ba6-82fafa465cbd.png)

**Comment by zhaoyunxing92** [comment]
这个bug理论上是maven的问题，我已经在几天前修复了这个问题[maven](https://github.com/apache/maven/pull/314)
