### ISSUE TITLE
start failed when upgrade to 2.7.5

### ISSUE THREAD

**Issue by kimifdw** [apache/dubbo-spring-boot-project#664]
当我把dubbo版本升级到2.7.5时, 项目启动失败了.我遇到了这样的一个错误：`FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: No application config found or it's not a valid config! Please add <dubbo:application name="..." /> to your spring config.`但在 dubbo版本为2.7.4.1，可以正常工作。我是通过@ImportResource来导入dubbo-provider.xml文件的

**Comment by mail6562** [comment]
[https://github.com/apache/dubbo-spring-boot-project/issues/657](url)

**Comment by mercyblitz** [comment]
Please upload your sample code!
