### ISSUE TITLE
isDefault 属性在SpringBoot的application.properties中报红

### ISSUE THREAD

**Issue by brucelwl** [apache/dubbo-spring-boot-project#673]
dubbo中很多配置类有```private Boolean isDefault;``` 字段,但是对该字段的Getter方法不是标准的，导致在SpringBoot的application.properties中会出现**红色**报警。
以注册中心为例
1、在单个注册配置的情况下，设置default不会报**红色**报警。  ```dubbo.registry.default=true```
2、但是在多注册中心配置的情况下，会**红色**报警。 ```dubbo.registries.zookeeper.default=false```

**解决办法:**
**将isDefault设置标准的Getter方法:** 
针对包装类型Boolean标准Getter方法应该是:  
```
//应该添加此方法,解决idea中配置提示,报红色问题
public Boolean getDefault() {
        return isDefault;
}
```
针对基本类型boolean标准Getter方法应该是:  
```
public Boolean isDefault() {
        return isDefault;
}
```
idea中显示如下:
![image](https://user-images.githubusercontent.com/13413715/72710697-9ba14680-3ba2-11ea-825b-3b789ae46d5e.png)

**Comment by mercyblitz** [comment]
Can you pull a request?
