### ISSUE TITLE
添加dubbo-spring-boot-*到dubbo-bom中

### ISSUE THREAD

**Issue by JasonMing** [apache/dubbo-spring-boot-project#678]
如果项目需要使用dubbo+spring-boot，并且规范两组依赖在同一版本，当前需要import dubbo-bom以及在dependencyManagement中定义dubbo-spring-boot-*依赖。
是否能把dubbo-spring-boot-*的定义也合并到dubbo-bom中？

**Comment by mercyblitz** [comment]
dubbo-bom just only focus on Duboo, but it's possible to add a bom named `dubbo-spring-boot-dependencies`

**Comment by JasonMing** [comment]
any support for dubbo-spring-boot-bom?

**Comment by AlbumenJ** [comment]
Currently dubbo-spring-boot-project has been merged back into apache-dubbo. `dubbo-spring-boot-dependencies` also has been merged in `dubbo-bom`.

**Comment by JasonMing** [comment]
@AlbumenJ  which version is that change applied, 3.x or 2.7.x ?

**Comment by AlbumenJ** [comment]
> @AlbumenJ which version is that change applied, 3.x or 2.7.x ?

Since 2.7.10.
