### ISSUE TITLE
docker 部署 dubbo-spring-boot项目时，生产者IP无法获取宿主机真实IP

### ISSUE THREAD

**Issue by zhonghang1993** [apache/dubbo-spring-boot-project#679]
各位开发者大佬们：
docker 部署 dubbo-spring-boot项目时，生产者IP无法获取宿主机真实IP，导致消费者无法正常调用生产者（找不到真实的服务提供者IP）。
经过大量测试配置dubbo.protocol.host为宿主机真实IP依然无效，还是获取的docker内的IP。
请问有什么合理的解决方案？

**Comment by jin82** [comment]
用环境变量，容器内部程序本身就获取不到宿主机Ip。如：
-e DUBBO_IP_TO_REGISTRY=x.x.x.x -e DUBBO_PORT_TO_REGISTRY=23000
