### ISSUE TITLE
springboot和dubbo一起用的时候@Service中的group 出现问题,provider中的group没用

### ISSUE THREAD

**Issue by LG991103** [apache/dubbo-spring-boot-project#681]
首先我用springboot整合dubbo   然后在消费者的Controller 声明了两个HelloService接口的对象 
   加上@Reference(group="A")和@Reference(group="B")  然后调用provider的方法 这时候group是没用作用的，我只能调用provider中 第一个实现了HelloService接口的类中的方法，调用HelloService接口的另一个实现类就报错，No provider available from registry 192.168.3.25:2181 for service Hello；这个Hello是我group的名字 
但是当我用spring整合dubbo 也写了一个一模一样的provider这时候我的消费者就可以通过分组调用
![image](https://user-images.githubusercontent.com/51302760/76316255-3f8eaf00-6315-11ea-8c9a-4a58f34d3390.png)

**Comment by leapcat** [comment]
I got the same problem

**Comment by mercyblitz** [comment]
How about your provider code?

**Comment by renshuajin** [comment]
我也是这个问题 ,2.7.5和2.7.6版本有这个问题,之前的2.7.4.1和2.7.3是正常的

**Comment by LiuJieTan** [comment]
老哥，解决了吗

**Comment by mercyblitz** [comment]
It will be fixed since 2.7.7.
