### ISSUE TITLE
Maven could not build while building the source code

### ISSUE THREAD

**Issue by qiaolin-li** [apache/dubbo-spring-boot-project#682]
The branch of the source code I'm currently building is  2.7.5

### He made the following mistake：

`[INFO] Building Apache Dubbo Spring Boot :: Compatible :: Auto-Configure 2.7.5
[INFO] ------------------------------------------------------------------------
Downloading: http://maven.aliyun.com/nexus/content/groups/public/org/apache/dubbo/dubbo-parent/$%7Brevision%7D/dubbo-parent-$%7Brevision%7D.pom
Downloading: http://repo.spring.io/milestone/org/apache/dubbo/dubbo-parent/$%7Brevision%7D/dubbo-parent-$%7Brevision%7D.pom
Downloading: http://repo.spring.io/snapshot/org/apache/dubbo/dubbo-parent/$%7Brevision%7D/dubbo-parent-$%7Brevision%7D.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache Dubbo Spring Boot :: Parent ................. SUCCESS [ 13.819 s]
[INFO] Apache Dubbo Spring Boot :: Compatible :: Auto-Configure FAILURE [  2.865 s]
[INFO] Apache Dubbo Spring Boot :: Compatible :: Actuator . SKIPPED
[INFO] Apache Dubbo Spring Boot :: Auto-Configure ......... SKIPPED
[INFO] Apache Dubbo Spring Boot :: Actuator ............... SKIPPED
[INFO] Apache Dubbo Spring Boot :: Starter ................ SKIPPED
[INFO] Apache Dubbo Spring Boot :: Distribution ........... SKIPPED
[INFO] Apache Dubbo Spring Boot :: Compatible ............. SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : API .......... SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Auto-Configure :: Consumer Sample SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Auto-Configure :: Provider Sample SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Auto-Configure SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Externalized Configuration :: Consumer Sample SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Externalized Configuration :: Provider Sample SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Externalized Configuration SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Registry Zookeeper :: Consumer Sample SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Registry Zookeeper :: Provider Sample SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Registry Zookeeper SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Registry Nacos :: Provider Sample SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Registry Nacos :: Consumer Sample SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples : Registry Nacos SKIPPED
[INFO] Apache Dubbo Spring Boot :: Samples ................ SKIPPED
[INFO] Apache Dubbo Spring Boot Project ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31.855 s
[INFO] Finished at: 2020-03-18T15:15:17+08:00
[INFO] Final Memory: 162M/901M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dubbo-spring-boot-autoconfigure-compatible: Could not resolve dependencies for project org.apache.dubbo:dubbo-spring-boot-autoconfigure-compatible:jar:2.7.5: Failed to collect dependencies at org.apache.dubbo:dubbo:jar:2.7.5: Failed to read artifact descriptor for org.apache.dubbo:dubbo:jar:2.7.5: Could not transfer artifact org.apache.dubbo:dubbo-parent:pom:${revision} from/to nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public/): TransferFailedException: ClientProtocolException: Invalid redirect URI: https://maven.aliyun.com/nexus/content/groups/public/org/apache/dubbo/dubbo-parent/${revision}/dubbo-parent-${revision}.pom: Illegal character in path at index 84: https://maven.aliyun.com/nexus/content/groups/public/org/apache/dubbo/dubbo-parent/${revision}/dubbo-parent-${revision}.pom -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dubbo-spring-boot-autoconfigure-compatible`

**Comment by qiaolin-li** [comment]
Using IDEA to update the dependency results in the following information:

Could not transfer artifact org.apache.dubbo:dubbo-parent:pom:${revision} from/to nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public/): TransferFailedException

**Comment by mercyblitz** [comment]
Please update your maven to be 3.5.0 and above
