### ISSUE TITLE
dubbo 2.7.5 启动失败,正则表达式匹配有问题

### ISSUE THREAD

**Issue by VbiosWen** [apache/dubbo-spring-boot-project#687]
org.apache.dubbo.config.ApplicationConfig#0 正则表达式在匹配这个名称时,无法匹配到特殊字符#号,抛出异常.
![image](https://user-images.githubusercontent.com/26213145/77824048-92040400-713a-11ea-865e-b5384ec4e7ea.png)
![image](https://user-images.githubusercontent.com/26213145/77824052-9c260280-713a-11ea-9c2f-cca5d7972a4a.png)
![image](https://user-images.githubusercontent.com/26213145/77824056-a34d1080-713a-11ea-9bbe-92939be87530.png)
![image](https://user-images.githubusercontent.com/26213145/77824061-ad6f0f00-713a-11ea-964c-2ec0743fe663.png)

**Comment by mercyblitz** [comment]
Please set the property `spring.application.name` or `dubbo.application.name` for current Spring Boot application.

**Comment by zywj** [comment]
@mercyblitz  It doesn't to work if only set `spring.application.name`.  It must set the `dubbo.application.name`.
