### ISSUE TITLE
provider start error

### ISSUE THREAD

**Issue by jianbingzhang** [apache/dubbo-spring-boot-project#693]
![image](https://user-images.githubusercontent.com/32535207/78665603-a8634a00-7908-11ea-8b9f-3d98b77d84f1.png)

java.lang.IllegalStateException: zookeeper not connected

**Comment by mail6562** [comment]
这个在windows 上有，还是linux上面都有？

**Comment by jianbingzhang** [comment]
> 这个在windows 上有，还是linux上面都有？

刚试了下，linux上没问题，windows上把zk的地址换了确实就连不上

**Comment by mercyblitz** [comment]
Please try 2.7.6
