### ISSUE TITLE
dubbo 2.7.1  集成springboot的时候，一直报22222端口占用。 

### ISSUE THREAD

**Issue by JackMore0328** [apache/dubbo-spring-boot-project#696]
dubbo 2.7.1  集成springboot的时候，一直报qos 22222端口占用。   但是我已经在yml配置中指定了33333端口，但是没有生效。 还是一直报端口占用。
以下是配置：
dubbo:
  application:
    qos-enable: true
    qos-port: 33333

**Comment by mercyblitz** [comment]
Please upgrade the latest version 2.7.6 to resolve this issue.
