### ISSUE TITLE
2.7.6版本会将Spring版本错误的引入4.3.16.RELEASE

### ISSUE THREAD

**Issue by JonChanGit** [apache/dubbo-spring-boot-project#697]
发现是以下依赖的问题
```
      <dependency>
        <groupId>org.apache.dubbo</groupId>
        <artifactId>dubbo-dependencies-bom</artifactId>
        <version>${dubbo.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

**Comment by mercyblitz** [comment]
I think it's fine because of `org.springframework.boot:spring-boot-dependencies` is declared at the top of `<dependencyManagement>`, Maven will override the same dependencies from `org.apache.dubbo:dubbo-dependencies-bom`.
