### ISSUE TITLE
java.lang.IllegalStateException: Failed to load extension class (interface: interface org.apache.dubbo.registry.RegistryFactory, class line: org.apache.dubbo.registry.nacos.NacosRegistryFactory)

### ISSUE THREAD

**Issue by eastlong** [apache/dubbo-spring-boot-project#698]
java.lang.IllegalStateException: Failed to load extension class (interface: interface org.apache.dubbo.registry.RegistryFactory, class line: org.apache.dubbo.registry.nacos.NacosRegistryFactory) in jar:file:/data/zeus/job_dir/2020-03-27/259692313/.jar!/META-INF/dubbo/internal/org.apache.dubbo.registry.RegistryFactory, cause: com/alibaba/nacos/api/exception/NacosException

Caused by: java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException

Caused by: java.lang.ClassNotFoundException: com.alibaba.nacos.api.exception.NacosException

**Comment by mercyblitz** [comment]
Please add the dependency :

```xml
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>${nacos.version}</version>
        </dependency>
```
