### ISSUE TITLE
boolean connected = client.blockUntilConnected(timeout, TimeUnit.MILLISECONDS); 超时时间怎么设置？

### ISSUE THREAD

**Issue by jiangbo123** [apache/dubbo-spring-boot-project#699]
boolean connected = client.blockUntilConnected(timeout, TimeUnit.MILLISECONDS);  ,  这里的timeout在哪里设置，dubbo.config-center.timeout 设置不管用，zk安装在阿里云上，本地连接大概需要10秒，但是默认的时5秒，导致报错：zookeeper not connected，就是这个超时时间的问题，如果把代码发布到阿里云服务器上面，就好了。
zk版本：3.5.7， springboot版本：2.x， dubbo-spring-boot-starter版本：2.7.5

**Comment by mercyblitz** [comment]
It's fixed on Dubbo 2.7.6

**Comment by joviqiao** [comment]
我tm就是2.7.6  还是有这个问题！！！！

**Comment by JohnnyLin12** [comment]
dubbo.config-center.timeout是设置读取dubbo配置中心的超时时间，默认为3000ms。dubbo.registry.timeout是设置连接注册中心zookeeper的超时时间，默认是5000ms，可尝试将后者值调大。
