### ISSUE TITLE
2.7.6版本 服务提供方开启多个实例后， 消费方@Reference注解如何配置

### ISSUE THREAD

**Issue by YourMightiness** [apache/dubbo-spring-boot-project#700]
1.目前提供方@Service(version = "1.0.0")，加入到nacos注册中心
消费方@Reference(version = "1.0.0",url = "dubbo://127.0.0.1:12345") 可以实现对12345端口的服务消费，但是nacos注册中心上未显示注册信息，

2.若开启多个服务提供方实例（如12345,12346）
请问消费方如何配置，@Reference(version = "1.0.0"）这样会失败
（nacos版本1.2.1，集合spring cloud alibaba 2.2.1）

**Comment by mercyblitz** [comment]
1. Using `@Reference(version = "1.0.0", url = "dubbo://127.0.0.1:12345")` is a direct connection to the Service provider, thus it will not register into any registry.

2. How about your code?
