### ISSUE TITLE
求一份zookeeper能连的版本号....

### ISSUE THREAD

**Issue by cy576013581** [apache/dubbo-spring-boot-project#705]
zookeeper版本：
Dubbo版本：
现在zookeeper用的3.5.5，dubbo用的2.7.6 一直有问题，链接不上，感觉dubbo到apache之后版本变动太乱了....

**Comment by mail6562** [comment]
有没有试过降低zookeeper，还能连接上么？

**Comment by cy576013581** [comment]
@mail6562 说3.4.15的好像，也不行

**Comment by mercyblitz** [comment]
Please upgrade the zookeeper client in your project.
