### ISSUE TITLE
使用dubbo2.7.6,使用nacos1.2.1，启动在nacos上服务都正常，但是消费端访问一直报no prplease check status of providers(disabled, not registered or in blacklist)

### ISSUE THREAD

**Issue by gang0713** [apache/dubbo-spring-boot-project#708]
使用dubbo2.7.6,使用nacos1.2.1，启动在nacos上服务都正常，但是消费端访问一直报no prplease check status of providers(disabled, not registered or in blacklist)，

后面发现把dubbo版本改为2.7.5，问题解决。

springboot 版本 2.2.6.RELEASE。

**Comment by gang0713** [comment]
可以使用https://gitee.com/liselotte/spring-boot-dubbo-demo，这个，改一下版本，验证一下。在这个上面也是一样的。

**Comment by mercyblitz** [comment]
Please try this way https://github.com/apache/dubbo/issues/5956

Or wait for 2.7.7.

**Comment by shenyao2333** [comment]
> 使用dubbo2.7.6,使用nacos1.2.1，启动在nacos上服务都正常，但是消费端访问一直报no prplease check status of providers(disabled, not registered or in blacklist)，
> 
> 后面发现把dubbo版本改为2.7.5，问题解决。
> 
> springboot 版本 2.2.6.RELEASE。

还是一样的，没解决
