### ISSUE TITLE
DubboConfigBeanDefinitionConflictApplicationListener -> resolveUniqueApplicationConfigBean

### ISSUE THREAD

**Issue by kylejucn** [apache/dubbo-spring-boot-project#710]
DubboConfigBeanDefinitionConflictApplicationListener -> resolveUniqueApplicationConfigBean
中针对 ApplicationConfig.class 的 beansNames.size() 必须一个的判断是否与 multiple = true相冲突？

**Comment by mercyblitz** [comment]
It's not conflicted, because `ApplicationConfig` Bean must be unique.
