### ISSUE TITLE
How to Reference a provider inside the LoadBalance？

### ISSUE THREAD

**Issue by sjtuzwj** [apache/dubbo-spring-boot-project#731]
I use data to load balance， and the data is stored in another provider.
![捕获](https://user-images.githubusercontent.com/32933716/86086693-e9689600-bad4-11ea-873f-f96dfef03794.JPG)
However,load balance itself is injected by @DubboReference(), and the inside reference will be null.

I wonder how to deal with it. Is there another way to put the data not locally?

**Comment by mercyblitz** [comment]
Please Use `@DubboReference#loadbalance()` attribute to specify your customized `LoadBalance`.
