### ISSUE TITLE
Problems of springboot Dubbo

### ISSUE THREAD

**Issue by liduanwen** [apache/dubbo-spring-boot-project#732]
Hello, at present, we integrate springboot 2.3.1+ Dubbo 2.7.7, and we will report this error at present  No registry config found or it's not a valid config! The registry config is: <dubbo:registry /> ，I read the source code, because application.yml The address of Dubbo's address was not loaded in。But when I introduce the dubbo-spring-boot-starter dependency, the problem is solved. Can you tell me the reason for the next block. thank you

**Comment by mercyblitz** [comment]
If you'd like to use Dubbo 2.7.x integrating with Spring Boot, please use `@EnableDubbo` and add some configurations like :
```properties
dubbo.application.name = app
...
```
