### ISSUE TITLE
@Reference 注解的url属性不管用

### ISSUE THREAD

**Issue by yibin001** [apache/dubbo-spring-boot-project#738]
想直连一个服务提供方，配置url属性不管用，只能按官方提供的三种方法了吗？

**Comment by mercyblitz** [comment]
Which version that you used?

**Comment by yibin001** [comment]
<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>2.7.3</version>
        </dependency>

**Comment by yibin001** [comment]
` @Reference(group = "TW",url = "dubbo://192.168.87.40:12333")
    IContractFundQueryService contractFundQueryService;`

这样还是会走注册中心，并不会直连到87.40这个服务提供方

**Comment by mercyblitz** [comment]
Please update the latest version
