### ISSUE TITLE
为什么 服务提供方 服务消费方 需要依赖同一个API接口模块？

### ISSUE THREAD

**Issue by GuoDapeng** [apache/dubbo-spring-boot-project#753]
为什么 服务提供方 服务消费方 需要依赖同一个API接口模块？

我是个新手，正在做微服务相关的学习。 dubbo 服务提供方 服务消费方 能不能不依赖同一个工程实现远程调用呢？我看到的 demo 全是依赖一个 API 的模块。

我现在很困惑……

**Comment by kylixs** [comment]
可以使用泛化调用，通过接口描述来调用，一般是网关上使用。
http://dubbo.apache.org/zh-cn/blog/dubbo-generic-invoke.html

**Comment by GuoDapeng** [comment]
> 可以使用泛化调用，通过接口描述来调用，一般是网关上使用。
> http://dubbo.apache.org/zh-cn/blog/dubbo-generic-invoke.html

十分感谢，即使我关闭了这个问题，还耐心的回答了我的问题。

我一会就去研究一下这个文档。

我还是个新手，在关闭这个问题后，我做了很多尝试，最后也达到了我想要的结果。

不知道这样是否礼貌，不礼貌的话就把我这条删除就好，我把自己实践的过程录了下来……

(Apache Dubbo：第一次接触 新手尝试)[https://www.bilibili.com/video/BV1eD4y197qE/]
