### ISSUE TITLE
NoSuchMethodError when using dubbo 2.7.9 

### ISSUE THREAD

**Issue by locuslin** [apache/dubbo-spring-boot-project#780]
dubbo-spring-boot version:2.7.8
dubbo version: 2.7.9

There is an error in DubboAutoConfiguration.java on line 83。

> 
	@Override
    public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
        if (applicationContext instanceof ConfigurableApplicationContext) {
            ConfigurableApplicationContext context = (ConfigurableApplicationContext) applicationContext;
            DubboLifecycleComponentApplicationListener dubboLifecycleComponentApplicationListener
                    = new DubboLifecycleComponentApplicationListener();
            dubboLifecycleComponentApplicationListener.setApplicationContext(applicationContext);
            context.addApplicationListener(dubboLifecycleComponentApplicationListener);

            DubboBootstrapApplicationListener dubboBootstrapApplicationListener = new DubboBootstrapApplicationListener();
            dubboBootstrapApplicationListener.setApplicationContext(applicationContext);
            context.addApplicationListener(dubboBootstrapApplicationListener);
        }
    }

`DubboLifecycleComponentApplicationListener` changed its construtor, and it requires `ApplicationContext`,the same as `DubboBootstrapApplicationListener`.

**Comment by Johnson-Jia** [comment]
臣附议，，赶紧改！！！

**Comment by AlbumenJ** [comment]
this would be fixed in https://github.com/apache/dubbo/pull/7357

**Comment by cssliuzhy** [comment]
2.7.9 还不发布呢？

**Comment by AlbumenJ** [comment]
Dubbo Spring Boot 2.7.9 has been released, pls try upgrade to it
