### ISSUE TITLE
dubbo3.0的什么时候支持？有无计划？2.7.10的也一直没有支持，能不能更新得快一点

### ISSUE THREAD

**Issue by gang0713** [apache/dubbo-spring-boot-project#788]
dubbo3.0的什么时候支持？有无计划？2.7.10的也一直没有支持，能不能更新得快一点

**Comment by AlbumenJ** [comment]
2.7.10 版本的 spring-boot-starter 已经跟随主版本一起发布了

3.0 的也将会在正式发版时同步支持

**Comment by dagmom** [comment]
3.0 released

**Comment by hugwh** [comment]
> 3.0 的也将会在正式发版时同步支持

dubbo 3.0 发布了

> 2.7.10 版本的 spring-boot-starter 已经跟随主版本一起发布了
> 
> 3.0 的也将会在正式发版时同步支持

dubbo 3.0发布了！期待支持！

**Comment by wklong** [comment]
> 2.7.10 版本的 spring-boot-starter 已经跟随主版本一起发布了
> 
> 3.0 的也将会在正式发版时同步支持

https://github.com/apache/dubbo-spring-boot-project 请问新版本的还是在这个地址吗? 我目前在这个地址看到的Releases 最新版为2.7.9   但是maven仓库看到最新版本为2.7.12

**Comment by AlbumenJ** [comment]
> > 2.7.10 版本的 spring-boot-starter 已经跟随主版本一起发布了
> > 3.0 的也将会在正式发版时同步支持
> 
> https://github.com/apache/dubbo-spring-boot-project 请问新版本的还是在这个地址吗? 我目前在这个地址看到的Releases 最新版为2.7.9 但是maven仓库看到最新版本为2.7.12

Spring Boot Starter 已经合并到 Dubbo 主仓库一起发布，目前在 https//github.com/apache/dubbo 中维护代码
