### ISSUE TITLE
dubbo3.0的spring boot什么时候出来？？？

### ISSUE THREAD

**Issue by startjava** [apache/dubbo-spring-boot-project#795]
dubbo3.0的spring boot什么时候出来？？？

**Comment by AlbumenJ** [comment]
dubbo 3.0 的使用和 2.7 一样

**Comment by yl-yue** [comment]
同时还有一个疑问，dubbo-spring-boot 和 grpc-spring-boot是冲突关系么？

**Comment by AlbumenJ** [comment]
> > dubbo 3.0 的使用和 2.7 一样
> 
> 容易有歧义，特别像我这种新入坑的，肯定想直接入手3.0，发现示例demo都是2.x的，又疑惑dubbo3与spring的关系，找到的资料都是2.x的，发现官方有对spring-boot支持，但也是2.x的，要不是看到这个疑问，可能就会认为dubbo3和spring-boot不用整合了。
> 
> 现在你的意思是，可以使用dubbo-spring-boot-project:2.7.9版本来使用dubbo3，只需要更改dubbo版本号，是这样么？

使用方式一样，版本号变更就行

**Comment by caofanqi** [comment]
直接使用3.0的starter即可  https://mvnrepository.com/artifact/org.apache.dubbo/dubbo-spring-boot-starter

**Comment by AlbumenJ** [comment]
This repo has been archived. All of the implements have been moved to [apache/dubbo](https://github.com/apache/dubbo). The latest version will be released with dubbo core.
