### ISSUE TITLE
歪歪歪，有人吗？为啥github上最新releases才到2.7.9？

### ISSUE THREAD

**Issue by l-qiang** [apache/dubbo-spring-boot-project#811]
2.7.9有问题呀，我一脚就是一个坑。
2.7.9在provider url没有group参数时，生成consumer的url时会加上group参数，导致No provider。
我人麻了！
跟我踩同样坑的兄弟升级版本就行了。
亲测2.7.15没问题

**Comment by ilaotan** [comment]
年久失修.唉....

**Comment by AlbumenJ** [comment]
This repo has been archived. All of the implements have been moved to [apache/dubbo](https://github.com/apache/dubbo). The latest version will be released with dubbo core.
