### ISSUE TITLE
此项目似乎已迁移至apache/dubbo/dubbo-spring-boot下，请更新一下文档说明

### ISSUE THREAD

**Issue by xishian** [apache/dubbo-spring-boot-project#814]
建议将此项目标记为archived，并说明新的仓库地址

**Comment by victory460** [comment]
m

**Comment by IOsetting** [comment]
> 建议将此项目标记为archived，并说明新的仓库地址

Could you please post the new repository URL? I cannot find it.

**Comment by xishian** [comment]
> > 建议将此项目标记为archived，并说明新的仓库地址
> 
> Could you please post the new repository URL? I cannot find it.

https://github.com/apache/dubbo
