### ISSUE TITLE
consumer use filer,@Reference service is null

### ISSUE THREAD

**Issue by l343765828** [apache/dubbo-spring-boot-project#816]
public class DubboLogFilter implements Filter {
    @Reference(version = "1.0.1",check = false)
    private GetId getid;

@Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        try {
            System.out.println("did：" + getid.getUidTest("a"));
        } catch (Exception e) {
            e.printStackTrace();
        }
        finally {
            return invoker.invoke(invocation);
        }
    }

GetId is null

dubbo version is 2.7.5, How to solve？

**Comment by l343765828** [comment]
@mercyblitz

**Comment by l343765828** [comment]
@AlbumenJ

**Comment by AlbumenJ** [comment]
Duplicated with https://github.com/apache/dubbo/issues/11539
