### ISSUE TITLE
能否通过springcontext 获取到bubbo的bean

### ISSUE THREAD

**Issue by star362** [apache/dubbo-spring-boot-project#817]
一个接口有两个实现类，使用不同的group 。在调用接口的时候需要根据不同的业务场景获取不同的实现类。类似于策略模式。所以我想通过getbean 的方式实现。请问可以吗？

**Comment by AlbumenJ** [comment]
通过 context 获取需要去判断 dubbo 生成名字的逻辑，建议直接通过注解注入使用

**Comment by star362** [comment]
通过注解也是可以实现的。不过我觉得代码写的不够优雅。需要写很多的 if else，我就是想知道是否能用代码实现。

**Comment by star362** [comment]
有没有什么代码参考。或者思路也行。

**Comment by star362** [comment]
@Component
public class TrilateralContext {

    @DubboReference(group = "maoyanTrilateralService", version = "1.0", check = false)
    TrilateralHandle trilateralHandle;


    public TrilateralHandle getTrilateralBean(String group) {
        BusinessAssert.notNull(group, BusinessCodeEnum.BAD_REQUEST, "group not null !!");
        return SpringUtil.getBean(ReferenceAnnotationBeanPostProcessor.class)
                .getReferenceBeans().stream()
                .filter(a -> a.getGroup().equals(group) && a.getObjectType() == TrilateralHandle.class)
                .map(a -> (TrilateralHandle) a.getObject()).findFirst().orElseThrow(() -> new BusinessException(BusinessCodeEnum.BAD_REQUEST, "获取 buddo 服务异常!!!"));

    }

}

我用的 ReferenceAnnotationBeanPostProcessor 也能获取到 dubbo 的服务。不过就是需要在这个类里边用@DubboReferenc 将服务引用进来。否则获取不到。
请问我这样写会有问题吗？

**Comment by star362** [comment]
@Component
public class TrilateralContext {

    @DubboReference(group = "Service", version = "1.0", check = false)
    TrilateralHandle trilateralHandle;


    public TrilateralHandle getTrilateralBean(String group) {
        Assert.notNull(group,  "group not null !!");
        return SpringUtil.getBean(ReferenceAnnotationBeanPostProcessor.class)
                .getReferenceBeans().stream()
                .filter(a -> a.getGroup().equals(group) && a.getObjectType() == TrilateralHandle.class)
                .map(a -> (TrilateralHandle) a.getObject()).findFirst().orElseThrow(() -> new IllegalArgumentException( "获取 buddo 服务异常!!!"));

    }

}

我用ReferenceAnnotationBeanPostProcessor 也可以实现，不过就是需要在类中添加   @DubboReference 否则就获取不到。
